### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by hariz-noob** [BedrockPlugins/BedrockMusic#1]
plugin error when I want to turn on the music error that is crash

**Comment by hariz-noob** [comment]
setelah saya lihat di console yg eror itu MusicAPI.php line 150
please fix plugin

**Comment by benjaminXYZ** [comment]
Please translate to english.

**Comment by ProtectorYT364** [comment]
after I saw on the console the error was MusicAPI.php line 150

**Comment by ProtectorYT364** [comment]
Translated

**Comment by benjaminXYZ** [comment]
Well this plugin is no longer up to date.
It has been more than one year and it does not support these versions.
Might update it when I got time
